version: "3"

services:
  frontend:
    image: nginx
    restart: always
    volumes:
      - ./dist:/usr/share/nginx/html
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:slamware.de"
      - "traefik.docker.network=traefik_net"
    networks:
      - traefik_net

networks:
  traefik_net:
    external: true


    
