version: '3'

services:
  hugo:
    container_name: hugo
    image: peaceiris/hugo
    volumes:
      - ./app:/src
    command:
      - server
      - --bind=0.0.0.0
    labels:
      - "traefik.enable=true"
      - "traefik.port=1313"
      - "traefik.frontend.rule=Host:slamware.de"
      - "traefik.docker.network=traefik_net"
